parserOptions:
  ecmaVersion: 2023
  sourceType: module

env:
  es2023: true
  browser: true
  node: true

extends: 'htmlacademy/vanilla'

rules:
  quotes: ['error', 'single', { avoidEscape: true }]
  indent: ['error', 2, { ignoredNodes: ['TemplateLiteral *'] }]

ignorePatterns:
  - webpack.config.js
